Hot start/stop mqtt stream is supported.
nanomq/nanomq pull request #1660
Opened 2024-02-05 06:56 UTC by wanghaEMQ

* Support start/stop via restapi.
* Add a Bool field enable_mqtt_stream to restapi.

2024-02-06 05:09 UTC, JaylinYu requested changes

2024-02-06 05:09 UTC, JaylinYu commented on nanomq/conf_api.c
> +				if (0 != nng_push0_open(hook_sock)) {
how about put this sock to conf?
Now it create a new socket each time calling HTTP

2024-02-06 09:51 UTC, JaylinYu approved these changes

2024-02-06 09:52 UTC, JaylinYu commented
surely there is still a lot to improve on details

2024-02-06 09:52 UTC, merged

2024-02-15 11:15 UTC, wanghaEMQ commented
> surely there is still a lot to improve on details

u are right