fix #1719
nanomq/nanomq pull request #1721
Opened 2024-03-26 06:18 UTC by OdyWayne

2024-03-26 07:19 UTC, OdyWayne commented on nanomq/webhook_post.c
for line 546 and line 554, if `parquet` and `blf` are both enabled then `flush_smsg_to_disk` will be called twice, but the `msgs_del` will be freed in the first called, then there will be a u-a-f. What is the business logic here，should we fix it? @xinyi-xs

2024-03-26 09:32 UTC, OdyWayne commented on nanomq/webhook_inproc.c
> +out:
`hook_search_reset_aio` is a global variable and is already decleared. `works` **is** alloced before line 714 in line 707.

2024-03-26 09:34 UTC, OdyWayne commented on nanomq/cmd_proc.c
> +	conf_fini(new_conf);
Yes ur right, it's a false positive.

2024-03-27 03:05 UTC, wanghaEMQ requested changes

2024-03-27 03:05 UTC, wanghaEMQ commented on nanomq/webhook_inproc.c
> +out:
Are u kidding me? Where will the works[0] be allocated?

2024-03-27 03:10 UTC, wanghaEMQ commented on nanomq/cmd_proc.c
> +	conf_fini(new_conf);
So... Fix it in another way?

2024-03-27 03:41 UTC, OdyWayne commented on nanomq/webhook_inproc.c
> +out:
compiler can deal with this as long as it is declared before.

2024-03-27 03:42 UTC, OdyWayne commented on nanomq/cmd_proc.c
> +	conf_fini(new_conf);
> So... Fix it in another way?

just ignore it, it's a **false positive**.

2024-03-28 05:11 UTC, OdyWayne commented on nanomq/webhook_inproc.c
> +out:
as you wish

2024-03-29 09:24 UTC, JaylinYu approved these changes

2024-03-29 09:26 UTC, JaylinYu commented on nanomq/webhook_post.c
for now, yes.
But might be 2 MQTT Stream object exists together in the future.

2024-03-29 09:27 UTC, JaylinYu commented
BLF & Parquet shall not be enabled together for now.

2024-03-29 09:44 UTC, wanghaEMQ approved these changes

2024-03-29 09:47 UTC, merged