* NEW [env] Support read environment variable for settings.
nanomq/nanomq pull request #299
Opened 2022-01-21 08:00 UTC by alvin1221

Implement [Support environment variables for settings. ](https://github.com/nanomq/nanomq/issues/291) #291

2022-01-21 08:23 UTC, lee-emqx approved these changes

2022-01-22 07:04 UTC, JaylinYu requested changes

2022-01-22 07:04 UTC, JaylinYu commented on README.md
> -
request for a demo

2022-01-22 07:49 UTC, JaylinYu approved these changes

2022-01-22 07:49 UTC, merged