For safety change return value of dbtree_find_client from db_ctxt to user ctxt.
nanomq/nanomq pull request #376
Opened 2022-03-01 08:19 UTC by lee-emqx

…_client and sync test.

2022-03-01 09:24 UTC, alvin1221 requested changes
Please mind that `Some checks were not successful`.

2022-03-01 11:00 UTC, lee-emqx commented
> Please mind that `Some checks were not successful`.

Thanks for remind, now it fixed.

2022-03-01 11:36 UTC, JaylinYu approved these changes

2022-03-02 01:16 UTC, JaylinYu approved these changes

2022-03-02 01:17 UTC, merged