Add mqtt5 codec
nanomq/nanomq pull request #377
Opened 2022-03-01 10:06 UTC by alvin1221

2022-03-02 03:09 UTC, wanghaEMQ commented on nanomq/sub_handler.c
> +			if ((topic_node_t = nng_zalloc(sizeof(topic_node))) ==
Why not nng_alloc?

2022-03-02 03:11 UTC, alvin1221 commented on nanomq/sub_handler.c
> +			if ((topic_node_t = nng_zalloc(sizeof(topic_node))) ==
```
void *
nni_alloc(size_t sz)
{
	return (sz > 0 ? malloc(sz) : NULL);
}

void *
nni_zalloc(size_t sz)
{
	return (sz > 0 ? calloc(1, sz) : NULL);
}
```

2022-03-06 04:33 UTC, JaylinYu commented on nanomq/unsub_handler.c
> +		encode_properties(msg, NULL);
this reduces performance

2022-03-08 09:21 UTC, JaylinYu requested changes
need more test

2022-03-08 09:21 UTC, JaylinYu commented on nanomq/apps/broker.c
> +			uint8_t  flag = *(body);
you can add the session present field here. but please get reason_code correctly.

2022-03-08 09:21 UTC, JaylinYu commented on nanomq/sub_handler.c
> +			if (conn_param_get_protover(work->cparam) ==
racing condition

2022-03-09 06:10 UTC, JaylinYu requested changes
racing condition everywhere

2022-03-09 06:10 UTC, JaylinYu commented on nanomq/pub_handler.c
>  {
what does this for?

2022-03-09 06:10 UTC, JaylinYu commented on nanomq/pub_handler.c
> +	proto = conn_param_get_protover(work->cparam);
racing condition

2022-03-09 07:45 UTC, JaylinYu commented
I am closing this due to PR moved

2022-03-09 07:45 UTC, closed without merging